# Generated by Django 3.2.8 on 2021-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=30)),
                ('chinese', models.IntegerField()),
                ('math', models.IntegerField()),
                ('english', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('allscore', models.IntegerField()),
            ],
        ),
    ]
